### ISSUE TITLE
Sorting by name on Shared Hosting is incorrect

### ISSUE THREAD

**Issue by alexmace** [phpversions/phpversions.info#294]
The shared hosting page is currently sorting alphabetically and by case. This seems wrong since it is "brand" names that are being sorted. e.g. names.co.uk now appears at the end, rather than in the middle.

**Comment by afelicioni** [comment]
Sorting issues are also occurring at javascript level, looking like unnatural/buggy also for different colums
![untitled](https://cloud.githubusercontent.com/assets/1416945/15081997/d3ef2510-13c5-11e6-843b-8bd68789d392.gif)

**Comment by philsturgeon** [comment]
Oh the sorting is so fucked. If you’d like to have a stab at sorting it out that would be amazing. 

-- 
Phil

On May 6, 2016 at 2:08:12 PM, Alessio Felicioni (notifications@github.com) wrote:

Sorting issues are also occurring at javascript level, looking like unnatural/buggy also for different colums

**Comment by afelicioni** [comment]
Little step for clientside sorting with #297 
Maybe version columns need custom type filter (with some javascript code additions in `js/main.js`)

**Comment by colinodell** [comment]
I think it was sorting based on the URL in the `<a>` tag.  This has been fixed in https://github.com/phpversions/phpversions.info/commit/5ca6e7e26bd86314a0c15780db1461e917e2bc9c.  Sorry this took 3 years :upside_down_face: Better late than never, right?
