### ISSUE TITLE
Find owner of domain name

### ISSUE THREAD

**Issue by matthewtrask** [phpversions/phpversions.info#472]
I need the domain name, so I can spin up a server and move things around since I have started rewriting this application. Do you know who has it?

**Comment by colinodell** [comment]
I would guess @philsturgeon (and if not, perhaps he would know)

**Comment by matthewtrask** [comment]
I asked him but he didnt know.

**Comment by petk** [comment]
If there is no known owner behind the domain it would be better to register a new one. Having foggy domain registered without knowing what's happening can be problematic as for cases like this, yes moving things and upgrading etc...

**Comment by philsturgeon** [comment]
Read above Harro, it’s not my domain and never was. I handed the project over years ago because I don’t do PHP work anymore. and I want this to be cared for.

**Comment by matthewtrask** [comment]
@WanWizard 

>Try to catch @philsturgeon when he's sober?

Thats not terribly nice to say on a project issues board. 

> It this also the reason why the data hasn't been updated the last 3 weeks?

The data has been getting updated via pull requests. If you see something wrong please make an issue.

**Comment by WanWizard** [comment]
Should have added a smiley, @philsturgeon and I go way back, he should know I didn't mean anything with it...

@matthewtrask All I can see is that the last pull was 19 days ago, for all sites on the managed services page. I checked because I wanted to remove the Exite entry (that company has stopped trading according to the link).

**Comment by matthewtrask** [comment]
I just merged two this morning. 

If you want to remove Exite, the best way right now would be to remove it from the correct yaml file.

**Comment by WanWizard** [comment]
Preparing a PR at the moment...

**Comment by matthewtrask** [comment]
Closing. 

Ive bought phpversions.net or something (cant remember off the top of my head). 

When we move to v2 (this year), the project will move with it. Im hoping I can do a 301 out of here to the new domain as well.
