### ISSUE TITLE
PHP 7.3 phpinfo files cannot be read

### ISSUE THREAD

**Issue by colinodell** [phpversions/phpversions.info#515]
There seems to be a bug in sturgeon/phparse: https://github.com/philsturgeon/phparse/pull/1. As a result, this project is unable to update PHP 7.3 infos.

I've submitted a PR to that project. If for any reason it can't be (or isn't) merged, I'll instead use https://github.com/cweagans/composer-patches to patch the library locally.

**Comment by matthewtrask** [comment]
@colinodell I dont think Phil is maintaining Phprase anymore, since he has moved to Ruby/JS work. 

I've gone ahead and forked it under this namespace so we can have access to it and do what we need to get it working.

**Comment by colinodell** [comment]
Thanks man!

**Comment by philsturgeon** [comment]
@matthewtrask hey if you want to delete yours I'll just transfer mine over so we dont have to have two repos floating around.
