### ISSUE TITLE
Entries seem to be there multiple times

### ISSUE THREAD

**Issue by heiglandreas** [phpversions/phpversions.info#528]
Looks like entries on the site are there multiple times. It looks like not only the last scan run is displayed but all scan runs. Is that necessary? 
![screenshot_20190215-062613](https://user-images.githubusercontent.com/91998/52836418-b9407300-30ea-11e9-8794-184eb33bc9ca.jpg)

**Comment by matthewtrask** [comment]
Are you on the old site (phpversion.info) or new (phpversions.org)? If its the new one, I just pushed up a fix.

**Comment by matthewtrask** [comment]
just deployed the new stuff, @heiglandreas can you look on phpversions.org and confirm you dont see dupe data?

**Comment by heiglandreas** [comment]
Looks much better! Thanks!!

**Comment by matthewtrask** [comment]
youre welcome!
