### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by colinodell** [phpversions/phpversions.info#555]
PHP 7.4 is just around the corner. We'll want to update the table output and version sorting to take those versions into account.

**Comment by coudenysj** [comment]
Anyone working on this already?

**Comment by colinodell** [comment]
I don't believe so.  I was going to start on it next week, but if you'd like to assist we'd appreciate the help!

There are essentially two changes that need to be made:

1. Add 7.4 to the tables and the "new and shiny" page, similar to https://github.com/phpversions/phpversions.info/commit/28cbffdc4e8f4e40ff02734e4cd66d7eb13a1ec0
2. Add 7.4 to the sorting functionality: https://github.com/phpversions/phpversions.info/blob/master/_plugins/sort.rb

Let me know if you're interested in helping here or if you have any questions!

**Comment by coudenysj** [comment]
Ok, I think I'll add a PR for it, because we're planning on adding the last RCs to our platform :).

**Comment by coudenysj** [comment]
Basic 7.4 information in #559.

I'm creating a new PR for "the new and shiny".
